{"name": "Повторная регистрация существующего пользователя", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_create_user.TestCreateUser object at 0x10c81e660>, register_new_user_return_login_and_password = []\n\n        @allure.title('Повторная регистрация существующего пользователя')\n        def test_register_created_user(self, register_new_user_return_login_and_password\n    ):\n            data = register_new_user_return_login_and_password\n    \n>           email = data[0]\nE           IndexError: list index out of range\n\ntests/test_create_user.py:30: IndexError"}, "start": 1721243782596, "stop": 1721243782596, "uuid": "a01f3b0f-99ba-4975-b2e3-70b9ee71282c", "historyId": "67bb644d9a03c7416c0fb5decdb26d82", "testCaseId": "67bb644d9a03c7416c0fb5decdb26d82", "fullName": "tests.test_create_user.TestCreateUser#test_register_created_user", "labels": [{"name": "suite", "value": "Создание нового пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "NB-ISC-14346"}, {"name": "thread", "value": "40631-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}